server:
  port: 8888
spring:
  application:
    name: service-config
  zipkin:
    base-url: http://localhost:9411
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hackyoMa/config-center.git
          search-paths: /respo
          username:
          password:
          clone-on-start: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8881/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"