server:
  port: 8885
spring:
  application:
    name: service-zuul
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8881/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
zuul:
  routes:
    feign:
      path: /feign/**
      serviceId: service-feign